# Air配置文件
# https://github.com/cosmtrek/air

root = "."
tmp_dir = "tmp"

[build]
# 构建命令
cmd = "go build -o ./tmp/main ."
# 构建后运行的二进制文件路径
bin = "./tmp/main"
# 监听以下类型的文件变动
include_ext = ["go", "yaml", "toml", "ini"]
# 忽略以下目录的变动
exclude_dir = ["tmp", "logs", "vendor"]
# 在变动后延迟多少毫秒重启
delay = 1000
# 环境变量
env = []

[log]
# 是否显示日志
time = true

[color]
# 日志颜色
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# 退出时是否删除tmp目录
clean_on_exit = true 